---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:us-east-2:170727074743:generatedTemplate/f86b2d7b-9cf8-46bd-a5c3-b40e46c9d346"
Parameters:
  KeyName:
    Default: "idea-engine-ec2-key"
    Type: "String"
    Description: "Name of an existing EC2 KeyPair to enable SSH access"
Resources:
  IAMRoleAWSServiceRoleForCloudFormationStackSetsOrgMember:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/aws-service-role/member.org.stacksets.cloudformation.amazonaws.com/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/aws-service-role/CloudFormationStackSetsOrgMemberServiceRolePolicy"
      MaxSessionDuration: 3600
      RoleName: "AWSServiceRoleForCloudFormationStackSetsOrgMember"
      Description: "Service linked role for CloudFormation StackSets (Organization\
        \ Member)"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "member.org.stacksets.cloudformation.amazonaws.com"
  EC2Instance:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EC2::Instance"
    DeletionPolicy: "Retain"
    Properties:
      Tenancy: "default"
      PrivateIpAddress: "172.31.16.154"
      MetadataOptions:
        HttpPutResponseHopLimit: 2
        HttpProtocolIpv6: "disabled"
        HttpTokens: "required"
        InstanceMetadataTags: "disabled"
        HttpEndpoint: "enabled"
      InstanceInitiatedShutdownBehavior: "stop"
      BlockDeviceMappings:
      - Ebs:
          SnapshotId: "snap-08e78047d7c596b4d"
          VolumeType: "gp3"
          Iops: 3000
          VolumeSize: 8
          Encrypted: false
          DeleteOnTermination: true
        DeviceName: "/dev/sda1"
      PrivateDnsNameOptions:
        EnableResourceNameDnsARecord: true
        HostnameType: "ip-name"
        EnableResourceNameDnsAAAARecord: false
      SecurityGroupIds:
      - "sg-0845f614589351f15"
      EbsOptimized: false
      DisableApiTermination: false
      SourceDestCheck: true
      PlacementGroupName: ""
      NetworkInterfaces:
      - Ipv6Addresses: []
        SecondaryPrivateIpAddressCount: 0
        NetworkInterfaceId: "eni-060b1c2ad2163b605"
        DeviceIndex: "0"
      ImageId: "ami-07062e2a343acc423"
      InstanceType: "t2.micro"
      Monitoring: false
      Tags:
      - Value: "idea-engine"
        Key: "Name"
      CreditSpecification:
        CPUCredits: "standard"
  ElastiCacheUser:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::ElastiCache::User"
    DeletionPolicy: "Retain"
    Properties:
      UserName: "default"
      UserId: "default"
      Engine: "redis"
      Tags: []
  EC2Volume:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EC2::Volume"
    DeletionPolicy: "Retain"
    Properties:
      MultiAttachEnabled: false
      SnapshotId: "snap-08e78047d7c596b4d"
      VolumeType: "gp3"
      Encrypted: false
      Size: 8
      AutoEnableIO: true
      AvailabilityZoneId: "use2-az2"
      AvailabilityZone: "us-east-2b"
      Throughput: 125
      Iops: 3000
      Tags: []
  IAMRoleAWSServiceRoleForOrganizations:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/aws-service-role/organizations.amazonaws.com/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/aws-service-role/AWSOrganizationsServiceTrustPolicy"
      MaxSessionDuration: 3600
      RoleName: "AWSServiceRoleForOrganizations"
      Description: "Service-linked role used by AWS Organizations to enable integration\
        \ of other AWS services with Organizations."
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "organizations.amazonaws.com"
  EC2Subnet:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EC2::Subnet"
    DeletionPolicy: "Retain"
    Properties:
      MapPublicIpOnLaunch: true
      EnableDns64: false
      VpcId: "vpc-05ad14e1092d25882"
      AvailabilityZoneId: "use2-az2"
      PrivateDnsNameOptionsOnLaunch:
        EnableResourceNameDnsARecord: false
        HostnameType: "ip-name"
        EnableResourceNameDnsAAAARecord: false
      AvailabilityZone: "us-east-2b"
      CidrBlock: "172.31.16.0/20"
      Ipv6Native: false
      Tags: []
  IAMRoleAWSReservedSSOtepmsbaIsbUsersPS82a37f3fac715752:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/aws-reserved/sso.amazonaws.com/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AdministratorAccess"
      MaxSessionDuration: 43200
      RoleName: "AWSReservedSSO_tepmsba_IsbUsersPS_82a37f3fac715752"
      Description: "User PermissionSet for the Innovation Sandbox on AWS solution"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              SAML:aud: "https://signin.aws.amazon.com/saml"
          Action:
          - "sts:AssumeRoleWithSAML"
          - "sts:TagSession"
          Effect: "Allow"
          Principal:
            Federated: "arn:aws:iam::170727074743:saml-provider/AWSSSO_5da700706eb366a5_DO_NOT_DELETE"
  IAMRoleIdeaenginebedrockrole:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AmazonBedrockFullAccess"
      - "arn:aws:iam::aws:policy/AWSMarketplaceRead-only"
      - "arn:aws:iam::aws:policy/AWSMarketplaceManageSubscriptions"
      MaxSessionDuration: 3600
      RoleName: "idea-engine-bedrock-role"
      Description: "Allows EC2 instances to call AWS services on your behalf."
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "ec2.amazonaws.com"
  EC2SecurityGroup:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EC2::SecurityGroup"
    DeletionPolicy: "Retain"
    Properties:
      GroupDescription: "default VPC security group"
      GroupName: "default"
      VpcId: "vpc-05ad14e1092d25882"
      SecurityGroupIngress:
      - IpProtocol: "-1"
        FromPort: -1
        SourceSecurityGroupId: "sg-0493f3eb32e630603"
        ToPort: -1
        SourceSecurityGroupOwnerId: "170727074743"
      SecurityGroupEgress:
      - CidrIp: "0.0.0.0/0"
        IpProtocol: "-1"
        FromPort: -1
        ToPort: -1
  IAMRoleAWSServiceRoleForTrustedAdvisor:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/aws-service-role/trustedadvisor.amazonaws.com/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/aws-service-role/AWSTrustedAdvisorServiceRolePolicy"
      MaxSessionDuration: 3600
      RoleName: "AWSServiceRoleForTrustedAdvisor"
      Description: "Access for the AWS Trusted Advisor Service to help reduce cost,\
        \ increase performance, and improve security of your AWS environment."
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "trustedadvisor.amazonaws.com"
  IAMRoleOrganizationAccountAccessRole:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AdministratorAccess"
      MaxSessionDuration: 3600
      RoleName: "OrganizationAccountAccessRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            AWS: "arn:aws:iam::978756215897:root"
  IAMRoleAWSServiceRoleForResourceExplorer:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/aws-service-role/resource-explorer-2.amazonaws.com/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/aws-service-role/AWSResourceExplorerServiceRolePolicy"
      MaxSessionDuration: 3600
      RoleName: "AWSServiceRoleForResourceExplorer"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "resource-explorer-2.amazonaws.com"
  IAMInstanceProfileIdeaenginebedrockrole:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::InstanceProfile"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      Roles:
      - "idea-engine-bedrock-role"
      InstanceProfileName: "idea-engine-bedrock-role"
  IAMRoleAWSReservedSSOtepmsbaIsbAdminsPSd193ab00356add09:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/aws-reserved/sso.amazonaws.com/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AdministratorAccess"
      MaxSessionDuration: 43200
      RoleName: "AWSReservedSSO_tepmsba_IsbAdminsPS_d193ab00356add09"
      Description: "Admin PermissionSet for the Innovation Sandbox on AWS solution"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              SAML:aud: "https://signin.aws.amazon.com/saml"
          Action:
          - "sts:AssumeRoleWithSAML"
          - "sts:TagSession"
          Effect: "Allow"
          Principal:
            Federated: "arn:aws:iam::170727074743:saml-provider/AWSSSO_5da700706eb366a5_DO_NOT_DELETE"
  EC2VPC:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EC2::VPC"
    DeletionPolicy: "Retain"
    Properties:
      CidrBlock: "172.31.0.0/16"
      EnableDnsSupport: true
      InstanceTenancy: "default"
      EnableDnsHostnames: true
      Tags: []
  EC2SecurityGroupXB:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EC2::SecurityGroup"
    DeletionPolicy: "Retain"
    Properties:
      GroupDescription: "launch-wizard-1 created 2026-04-03T03:01:09.166Z"
      GroupName: "launch-wizard-1"
      VpcId: "vpc-05ad14e1092d25882"
      SecurityGroupIngress:
      - CidrIp: "0.0.0.0/0"
        IpProtocol: "tcp"
        FromPort: 22
        ToPort: 22
      - CidrIp: "0.0.0.0/0"
        IpProtocol: "tcp"
        FromPort: 8501
        ToPort: 8501
      - CidrIp: "0.0.0.0/0"
        IpProtocol: "tcp"
        FromPort: 443
        ToPort: 443
      SecurityGroupEgress:
      - CidrIp: "0.0.0.0/0"
        IpProtocol: "-1"
        FromPort: -1
        ToPort: -1
  EC2VolumeAttachment:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EC2::VolumeAttachment"
    DeletionPolicy: "Retain"
    Properties:
      VolumeId: "vol-00abd044f3ad24cbe"
      InstanceId: "i-07d1db4cc01d456a4"
      Device: "/dev/sda1"
      EbsCardIndex: 0
  EC2NetworkInterface:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EC2::NetworkInterface"
    DeletionPolicy: "Retain"
    Properties:
      SourceDestCheck: true
      InterfaceType: "interface"
      Description: ""
      PrivateIpAddress: "172.31.16.154"
      SecondaryPrivateIpAddressCount: 0
      Ipv6PrefixCount: 0
      Ipv4Prefixes: []
      Ipv4PrefixCount: 0
      GroupSet:
      - "sg-0845f614589351f15"
      Ipv6Prefixes: []
      SubnetId: "subnet-0edbd81dedde7feea"
      Tags: []
  IAMRoleAWSServiceRoleForSSO:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/aws-service-role/sso.amazonaws.com/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/aws-service-role/AWSSSOServiceRolePolicy"
      MaxSessionDuration: 3600
      RoleName: "AWSServiceRoleForSSO"
      Description: "Service-linked role used by AWS SSO to manage AWS resources, including\
        \ IAM roles, policies and SAML IdP on your behalf."
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "sso.amazonaws.com"
  IAMRoleAWSReservedSSOtepmsbaIsbManagersPSd1f89ac071a91210:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/aws-reserved/sso.amazonaws.com/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AdministratorAccess"
      MaxSessionDuration: 43200
      RoleName: "AWSReservedSSO_tepmsba_IsbManagersPS_d1f89ac071a91210"
      Description: "Manager PermissionSet for the Innovation Sandbox on AWS solution"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              SAML:aud: "https://signin.aws.amazon.com/saml"
          Action:
          - "sts:AssumeRoleWithSAML"
          - "sts:TagSession"
          Effect: "Allow"
          Principal:
            Federated: "arn:aws:iam::170727074743:saml-provider/AWSSSO_5da700706eb366a5_DO_NOT_DELETE"
  IAMRoleAWSServiceRoleForCloudTrail:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/aws-service-role/cloudtrail.amazonaws.com/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/aws-service-role/CloudTrailServiceRolePolicy"
      MaxSessionDuration: 3600
      RoleName: "AWSServiceRoleForCloudTrail"
      Description: "This service-linked role is used for supporting organization trail\
        \ feature"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "cloudtrail.amazonaws.com"
  IAMRoleAWSServiceRoleForSupport:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/aws-service-role/support.amazonaws.com/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/aws-service-role/AWSSupportServiceRolePolicy"
      MaxSessionDuration: 3600
      RoleName: "AWSServiceRoleForSupport"
      Description: "Enables resource access for AWS to provide billing, administrative\
        \ and support services"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "support.amazonaws.com"
